//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Twitter_API2_Stream_Test {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings1 : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings1 defaultInstance = ((Settings1)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings1())));
        
        public static Settings1 Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("AAAAAAAAAAAAAAAAAAAAAF%2FtlgEAAAAALkzMo2giThlOWBtaUrSlqc9AN1U%3DhLRHQ0CKojo7Gkara" +
            "qJDSsC5y9ilvn3QdbraTceNzbXFOrrt2D")]
        public string Bearer_Token {
            get {
                return ((string)(this["Bearer_Token"]));
            }
            set {
                this["Bearer_Token"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.twitter.com/2/tweets/recent/stream")]
        public string Total_Stream_Endpoint {
            get {
                return ((string)(this["Total_Stream_Endpoint"]));
            }
            set {
                this["Total_Stream_Endpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.twitter.com/2/tweets/search/recent?query=%23hashtag&max_results=100")]
        public string Top10HashTags_Endpoint {
            get {
                return ((string)(this["Top10HashTags_Endpoint"]));
            }
            set {
                this["Top10HashTags_Endpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://api.twitter.com/2/tweets/search/recent")]
        public string Recent_Tweets_Endpoint {
            get {
                return ((string)(this["Recent_Tweets_Endpoint"]));
            }
            set {
                this["Recent_Tweets_Endpoint"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\\\error.log")]
        public string Error_LogFile {
            get {
                return ((string)(this["Error_LogFile"]));
            }
            set {
                this["Error_LogFile"] = value;
            }
        }
    }
}
